language: java

jdk:
  - oraclejdk8

sudo: false

addons:
  chrome: stable

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew -Dgeb.env=chrome-headless check

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true

after_success:
  - ls -l rollup/dist/
